// Gruvbox color palette for syntax highlighting
export const gruvboxDark = {
  'code[class*="language-"]': {
    color: '#ebdbb2',
    background: 'none',
    fontFamily:
      'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace',
    fontSize: '14px',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.6',
    tabSize: 2,
  },
  'pre[class*="language-"]': {
    color: '#ebdbb2',
    background: '#1d2021',
    fontFamily:
      'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace',
    fontSize: '14px',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.6',
    tabSize: 2,
    padding: '1rem',
    margin: '0',
    overflow: 'auto',
    borderRadius: '0.5rem',
  },
  comment: { color: '#928374', fontStyle: 'italic' },
  prolog: { color: '#928374' },
  doctype: { color: '#928374' },
  cdata: { color: '#928374' },
  punctuation: { color: '#ebdbb2' },
  property: { color: '#fb4934' },
  tag: { color: '#fb4934' },
  boolean: { color: '#d3869b' },
  number: { color: '#d3869b' },
  constant: { color: '#d3869b' },
  symbol: { color: '#d3869b' },
  deleted: { color: '#fb4934' },
  selector: { color: '#b8bb26' },
  'attr-name': { color: '#b8bb26' },
  string: { color: '#b8bb26' },
  char: { color: '#b8bb26' },
  builtin: { color: '#b8bb26' },
  inserted: { color: '#b8bb26' },
  operator: { color: '#fe8019' },
  entity: { color: '#fe8019', cursor: 'help' },
  url: { color: '#fe8019' },
  '.language-css .token.string': { color: '#fe8019' },
  '.style .token.string': { color: '#fe8019' },
  variable: { color: '#fe8019' },
  atrule: { color: '#fabd2f' },
  'attr-value': { color: '#fabd2f' },
  function: { color: '#fabd2f' },
  'class-name': { color: '#fabd2f' },
  keyword: { color: '#fb4934' },
  regex: { color: '#8ec07c' },
  important: { color: '#8ec07c', fontWeight: 'bold' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
};

export const gruvboxLight = {
  'code[class*="language-"]': {
    color: '#3c3836',
    background: 'none',
    fontFamily:
      'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace',
    fontSize: '14px',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.6',
    tabSize: 2,
  },
  'pre[class*="language-"]': {
    color: '#3c3836',
    background: '#fffef2',
    fontFamily:
      'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace',
    fontSize: '14px',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.6',
    tabSize: 2,
    padding: '1rem',
    margin: '0',
    overflow: 'auto',
    borderRadius: '0.5rem',
  },
  comment: { color: '#928374', fontStyle: 'italic' },
  prolog: { color: '#928374' },
  doctype: { color: '#928374' },
  cdata: { color: '#928374' },
  punctuation: { color: '#3c3836' },
  property: { color: '#9d0006' },
  tag: { color: '#9d0006' },
  boolean: { color: '#8f3f71' },
  number: { color: '#8f3f71' },
  constant: { color: '#8f3f71' },
  symbol: { color: '#8f3f71' },
  deleted: { color: '#9d0006' },
  selector: { color: '#79740e' },
  'attr-name': { color: '#79740e' },
  string: { color: '#79740e' },
  char: { color: '#79740e' },
  builtin: { color: '#79740e' },
  inserted: { color: '#79740e' },
  operator: { color: '#af3a03' },
  entity: { color: '#af3a03', cursor: 'help' },
  url: { color: '#af3a03' },
  '.language-css .token.string': { color: '#af3a03' },
  '.style .token.string': { color: '#af3a03' },
  variable: { color: '#af3a03' },
  atrule: { color: '#b57614' },
  'attr-value': { color: '#b57614' },
  function: { color: '#b57614' },
  'class-name': { color: '#b57614' },
  keyword: { color: '#9d0006' },
  regex: { color: '#427b58' },
  important: { color: '#427b58', fontWeight: 'bold' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
};
